import { Navbar } from "@/components/Navbar"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Toaster } from "@/components/ui/toaster"
import { Provider } from "@/providers/SessionProvider"
import { ModalProvider } from "@/components/modal/modal-provider"
import { Footer } from "@/components/Footer"
import { useModalEntranceStore } from "@/context/modal-entrance-store"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt">
      <body
        className={`${inter.className} bg-[url('/bg/bg-rainbow.jpg')] bg-cover bg-center bg-no-repeat w-full min-h-screen`}
      >
        <Provider>
          <main className=" flex flex-col items-center">
            <Toaster />
            <Navbar />
            <ModalProvider>{children}</ModalProvider>
            {/* <Footer /> */}
          </main>
        </Provider>
      </body>
    </html>
  )
}
